server:
  port: 9090
  servlet:
    context-path: /yingxue
    jsp:
      init-parameters:
        development: true
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yingxue
    password: root
    username: root
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  redis:
    host: 106.12.149.196    #ip
    port: 7000    #端口
    database: 3   #操作的库
  data:
    elasticsearch:
      cluster-nodes: 106.12.149.196:9300
mybatis:
  type-aliases-package: com.baizhi.zyp.entity
  mapper-locations: classpath:com/baizhi/zyp/mapper/*Mapper.xml
